#Workflow name
name: 'Backend Github Workflow CI'

run-name: ${{ github.actor }} is trigger this ${{ github.workflow }}

on: 
  pull_request:
    branches: [main]
    paths: 
      - starter/backend
  
  push:
    branches: [main]
    paths:
      - starter/backend
      
  # Manual trigger using the workflow_dispatch event
  # workflow_dispatch:
   
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true    
  
# Jobs defined in the workflow           
jobs:
  lint_and_test:
    uses: ./.github/workflows/backend-lint-test.yml
  