#Workflow name
name: 'Linting and testing workflow for Backend CI'

run-name: ${{ github.actor }} is trigger this ${{ github.workflow }}

# Triggers for the workflow
on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        required: false
        type: string
        default: '3.10'
      working-directory:
        description: 'Working directory'
        required: false
        type: string
        default: starter/backend
    
# Jobs defined in the workflow           
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
        working-directory: ${{ inputs.working-directory}}
    steps:
      # This step checks out a copy of source code in target branch of your repository
      - name: Checkout Repository
        uses: actions/checkout@v4 
                
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv wheel
          pipenv install --dev
  
      - name: Lint code
        run: pipenv run lint
  
  test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
        working-directory: ${{ inputs.working-directory}}
    steps:
      # This step checks out a copy of source code in target branch of your repository
      - name: Checkout Repository
        uses: actions/checkout@v4 
                
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv wheel
          pipenv install --dev
          
      - name: Run test suite
        run: |
          pipenv run test