#Workflow name
name: 'Linting and testing workflow for Backend CI'

run-name: ${{ github.actor }} is trigger this ${{ github.workflow }}

# Triggers for the workflow
on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        required: false
        type: string
        default: '3.10'
      working-directory:
        description: 'Working directory'
        required: false
        type: string
        default: starter/backend
                
# Jobs defined in the workflow           
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
        working-directory: ${{ inputs.working-directory}}
    outputs:
      working-directory: ${{ inputs.working-directory}}
    steps:
      # This step checks out a copy of source code in target branch of your repository
      - name: Checkout Repository
        uses: actions/checkout@v4 
                
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
          
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install
          
      - name: Run test suite
        run: |
          pipenv run test

      - name: Run linter
        run: |
          pipenv run lint
  test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
        working-directory: ${{ inputs.working-directory}}
    steps:
      # This step checks out a copy of source code in target branch of your repository
      - name: Checkout Repository
        uses: actions/checkout@v4 
                
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
          
      - id: cache-pipenv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install
          
      - name: Run test suite
        run: |
          pipenv run test