#Workflow name
name: 'Frontend Github Workflow CI'

run-name: ${{ github.actor }} is trigger this ${{ github.workflow }}

# Triggers for the workflow
on:
   # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
    
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
    paths: 
      - starter/frontend
      - ./.github
  
  push:
    branches: [main]
    paths: 
      - starter/frontend
      - ./.github
    
permissions:
  contents: read
  pull-requests: read
  
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true    
  
# Jobs defined in the workflow           
jobs:
  lint_and_test:
    uses: ./.github/workflows/frontend-lint-test.yaml
      
  build:
    needs: lint_and_test
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
        working-directory: ${{ needs.lint_and_test.outputs.working-directory}}
    steps:
      # This step checks out a copy of source code in target branch of your repository
      - name: Checkout Repository
        uses: actions/checkout@v4 
        
      - name: Build
        run: npm run build
    
  