#Workflow name
name: 'Frontend Github Workflow CI'

run-name: ${{ github.actor }} is trigger this ${{ github.workflow }}

on: 
  pull_request:
    branches: [main]
    paths: 
      - starter/frontend/**
      
  workflow_dispatch:
  
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true  
  
# Jobs defined in the workflow           
jobs:
  lint_and_test:
    uses: ./.github/workflows/frontend-lint-test.yml
    
  build:
    needs: lint_and_test
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
        working-directory: 'starter/frontend'
    steps:
      # This step checks out a copy of source code in target branch of your repository
      - name: Checkout Repository
        uses: actions/checkout@v4 
        
      - name: Set up nodejs
        uses: actions/setup-node@v4
        with: 
          node-version-file: 'starter/frontend/.nvmrc'
          check-latest: false
          cache: 'npm'
          cache-dependency-path: 'starter/frontend/package-lock.json'
                
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
    
  